@startuml
interface Notificador {
  + enviar(msj: String): void
}
class NotificadorEmail {
  + enviar(msj: String): void
}
abstract class DecoradorNotificador {
  # envoltorio: Notificador
  + enviar(msj: String): void
}
class NotificadorSMS {
  + enviar(msj: String): void
}
NotificadorEmail ..|> Notificador
DecoradorNotificador ..|> Notificador
DecoradorNotificador o--> Notificador
NotificadorSMS --|> DecoradorNotificador
@enduml