@startuml
interface Builder {
  + conMasa(masa: String): Builder
  + conSalsa(salsa: String): Builder
  + build(): Pizza
}
class PizzaBuilder {
  - pizza: Pizza
  + conMasa(masa: String): PizzaBuilder
  + conSalsa(salsa: String): PizzaBuilder
  + build(): Pizza
}
class Pizza {
  - masa: String
  - salsa: String
}
PizzaBuilder ..|> Builder
PizzaBuilder --> Pizza
@enduml